import db from "./db";
import {
    UserTable,
    HotelTable,
    RoomTable,
    BookingTable,
    PaymentTable,
    CustomerSupportTable
} from "./schema";

async function seed() {
    console.log('Seeding database...');

    // Seed Users (10 records)
    await db.insert(UserTable).values([
        {
            first_name: "Alice",
            last_name: "Kimani",
            email: "alice.kimani@example.com",
            password: "hashedpassword1",
            role: "user",
            is_verified: false,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            first_name: "John",
            last_name: "Doe",
            email: "john.doe@gmail.com",
            password: "hashedpassword2",
            role: "user",
            is_verified: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            first_name: "Jane",
            last_name: "Wanjiku",
            email: "jane.wanjiku@example.com",
            password: "hashedpassword3",
            role: "user",
            is_verified: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            first_name: "Bob",
            last_name: "Otieno",
            email: "bob.otieno@example.com",
            password: "hashedpassword4",
            role: "admin",
            is_verified: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            first_name: "Emma",
            last_name: "Njoroge",
            email: "emma.njoroge@example.com",
            password: "hashedpassword5",
            role: "user",
            is_verified: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            first_name: "Michael",
            last_name: "Kariuki",
            email: "michael.kariuki@example.com",
            password: "hashedpassword6",
            role: "user",
            is_verified: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            first_name: "Sarah",
            last_name: "Muthoni",
            email: "sarah.muthoni@example.com",
            password: "hashedpassword7",
            role: "user",
            is_verified: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            first_name: "David",
            last_name: "Kamau",
            email: "david.kamau@example.com",
            password: "hashedpassword8",
            role: "admin",
            is_verified: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            first_name: "Grace",
            last_name: "Achieng",
            email: "grace.achieng@example.com",
            password: "hashedpassword9",
            role: "user",
            is_verified: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            first_name: "Peter",
            last_name: "Onyango",
            email: "peter.onyango@example.com",
            password: "hashedpassword10",
            role: "user",
            is_verified: true,
            created_at: new Date(),
            updated_at: new Date(),
        }
    ]).returning();

    // Seed Hotels (10 records)
    await db.insert(HotelTable).values([
        {
            name: "Sunset Paradise",
            location: "Mombasa Beach",
            address: "123 Ocean Drive, Mombasa",
            contact_number: "+254700000001",
            category: "Resort",
            rating: 5,
            img_url: "https://example.com/hotel1.jpg",
            description: "A luxurious beachfront resort with stunning ocean views.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: "Mountain View Lodge",
            location: "Mt. Kenya",
            address: "456 Summit Road, Nanyuki",
            contact_number: "+254700000002",
            category: "Lodge",
            img_url: "https://example.com/hotel2.jpg",
            description: "A cozy lodge nestled in the mountains with breathtaking views.",
            rating: 4,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: "Cityscape Hotel",
            location: "Nairobi CBD",
            address: "789 Kenyatta Avenue, Nairobi",
            contact_number: "+254700000003",
            category: "Hotel",
            rating: 3,
            img_url: "https://example.com/hotel3.jpg",
            description: "A modern hotel in the heart of the city, perfect for business travelers.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: "Safari Haven",
            location: "Maasai Mara",
            address: "101 Savanna Road, Narok",
            contact_number: "+254700000004",
            category: "Camp",
            rating: 5,
            img_url: "https://example.com/hotel4.jpg",
            description: "An adventurous camp offering safari experiences in the Maasai Mara.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: "Coastal Breeze",
            location: "Diani Beach",
            address: "202 Beach Road, Diani",
            contact_number: "+254700000005",
            category: "Resort",
            rating: 4,
            img_url: "https://example.com/hotel5.jpg",
            description: "A serene resort with private beach access and water sports activities.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: "Lakeside Retreat",
            location: "Lake Naivasha",
            address: "303 Lakeview Drive, Naivasha",
            contact_number: "+254700000006",
            category: "Lodge",
            img_url: "https://example.com/hotel6.jpg",
            description: "A peaceful lodge by the lake, ideal for nature lovers and bird watchers.",
            rating: 4,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: "Urban Oasis",
            location: "Westlands, Nairobi",
            address: "404 Park Road, Nairobi",
            contact_number: "+254700000007",
            category: "Hotel",
            rating: 3,
            img_url: "https://example.com/hotel10.jpg",
            description: "A modern oasis in the city with excellent amenities.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: "Serengeti Lodge",
            location: "Amboseli",
            address: "505 Plains Road, Amboseli",
            contact_number: "+254700000008",
            category: "Lodge",
            rating: 5,
            img_url: "https://example.com/hotel7.jpg",
            description: "A luxurious lodge with views of Mount Kilimanjaro and wildlife safaris.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: "Coral Reef Resort",
            location: "Lamu Island",
            address: "606 Coral Street, Lamu",
            contact_number: "+254700000009",
            category: "Resort",
            rating: 4,
            img_url: "https://example.com/hotel8.jpg",
            description: "A tropical resort with coral reefs, perfect for diving and relaxation.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: "Highland Inn",
            location: "Nyeri",
            address: "707 Hill Road, Nyeri",
            contact_number: "+254700000010",
            category: "Hotel",
            rating: 3,
            img_url: "https://example.com/hotel9.jpg",
            description: "A charming inn in the highlands, offering a peaceful retreat.",
            created_at: new Date(),
            updated_at: new Date(),
        }
    ]).returning();

    // Seed Rooms (10 records, distributed across hotels)
    await db.insert(RoomTable).values([
        {
            hotel_id: 1,
            room_number: "101",
            room_type: "Deluxe",
            price_per_night: 12000,
            capacity: 2,
            amenities: "WiFi,TV,AC",
            availability: "available",
            img_url: "https://example.com/room1.jpg",
            description: "A spacious deluxe room with ocean views and modern amenities.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            hotel_id: 1,
            room_number: "102",
            room_type: "Standard",
            price_per_night: 8000,
            capacity: 2,
            amenities: "WiFi,TV",
            availability: "available",
            img_url: "https://example.com/room2.jpg",
            description: "A comfortable standard room with all basic amenities.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            hotel_id: 2,
            room_number: "201",
            room_type: "Suite",
            price_per_night: 20000,
            capacity: 4,
            amenities: "WiFi,TV,AC,Mini Bar",
            availability: "available",
            img_url: "https://example.com/room3.jpg",
            description: "A luxurious suite with a separate living area and stunning mountain views.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            hotel_id: 3,
            room_number: "301",
            room_type: "Single",
            price_per_night: 6000,
            capacity: 1,
            amenities: "WiFi,TV",
            availability: "booked",
            img_url: "https://example.com/room4.jpg",
            description: "A cozy single room, perfect for solo travelers.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            hotel_id: 4,
            room_number: "401",
            room_type: "Tent",
            price_per_night: 15000,
            capacity: 2,
            amenities: "WiFi,Outdoor Shower",
            availability: "available",
            img_url: "https://example.com/room5.jpg",
            description: "A unique tent experience with luxury amenities in the heart of the savanna.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            hotel_id: 5,
            room_number: "501",
            room_type: "Deluxe",
            price_per_night: 14000,
            capacity: 3,
            amenities: "WiFi,TV,AC,Balcony",
            availability: "available",
            img_url: "https://example.com/room6.jpg",
            description: "A deluxe room with a private balcony overlooking the beach.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            hotel_id: 6,
            room_number: "601",
            room_type: "Cottage",
            price_per_night: 18000,
            capacity: 4,
            amenities: "WiFi,TV,Fireplace",
            availability: "booked",
            img_url: "https://example.com/room7.jpg",
            description: "A charming cottage with a fireplace, perfect for family getaways.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            hotel_id: 7,
            room_number: "701",
            room_type: "Standard",
            price_per_night: 9000,
            capacity: 2,
            amenities: "WiFi,TV",
            availability: "available",
            img_url: "https://example.com/room8.jpg",
            description: "A standard room with essential amenities for a comfortable stay.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            hotel_id: 8,
            room_number: "801",
            room_type: "Suite",
            price_per_night: 22000,
            capacity: 4,
            amenities: "WiFi,TV,AC,Hot Tub",
            availability: "available",
            img_url: "https://example.com/room9.jpg",
            description: "A luxurious suite with a hot tub and panoramic views of the ocean.",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            hotel_id: 9,
            room_number: "901",
            room_type: "Deluxe",
            price_per_night: 13000,
            capacity: 3,
            amenities: "WiFi,TV,AC,Ocean View",
            availability: "booked",
            img_url: "https://example.com/room10.jpg",
            description: "A deluxe room with ocean view and modern amenities.",
            created_at: new Date(),
            updated_at: new Date(),
        }
    ]).returning();

    // Seed Bookings (10 records, linked to users, hotels, and rooms)
    await db.insert(BookingTable).values([
        {
            user_id: 1,
            hotel_id: 1,
            room_id: 1,
            check_in_date: '2023-10-01',
            check_out_date: '2023-10-03',
            total_amount: 24000, // 2 nights * 12000
            status: "confirmed",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 2,
            hotel_id: 2,
            room_id: 3,
            check_in_date: '2023-10-02',
            check_out_date: '2023-10-05',
            total_amount: 60000, // 3 nights * 20000
            status: "pending",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 3,
            hotel_id: 3,
            room_id: 4,
            check_in_date: '2023-10-03',
            check_out_date: '2023-10-04',
            total_amount: 6000, // 1 night * 6000
            status: "confirmed",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 4,
            hotel_id: 4,
            room_id: 5,
            check_in_date: '2023-10-04',
            check_out_date: '2023-10-06',
            total_amount: 30000, // 2 nights * 15000
            status: "confirmed",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 5,
            hotel_id: 5,
            room_id: 6,
            check_in_date: '2023-10-05',
            check_out_date: '2023-10-08',
            total_amount: 42000, // 3 nights * 14000
            status: "pending",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 6,
            hotel_id: 6,
            room_id: 7,
            check_in_date: '2023-10-06',
            check_out_date: '2023-10-08',
            total_amount: 36000, // 2 nights * 18000
            status: "confirmed",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 7,
            hotel_id: 7,
            room_id: 8,
            check_in_date:'2023-10-07',
            check_out_date: '2023-10-08',
            total_amount: 9000, // 1 night * 9000
            status: "pending",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 8,
            hotel_id: 8,
            room_id: 9,
            check_in_date: '2023-10-08',
            check_out_date: '2023-10-10',
            total_amount: 44000, // 2 nights * 22000
            status: "confirmed",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 9,
            hotel_id: 9,
            room_id: 10,
            check_in_date: '2023-10-09',
            check_out_date: '2023-10-11',
            total_amount: 26000, // 2 nights * 13000
            status: "confirmed",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 10,
            hotel_id: 10,
            room_id: 2,
            check_in_date: '2023-10-10',
            check_out_date: '2023-10-12',
            total_amount: 8000, // 1 night * 8000
            status: "pending",
            created_at: new Date(),
            updated_at: new Date(),
        }
    ]).returning();

    // Seed Payments (10 records, linked to bookings)
    await db.insert(PaymentTable).values([
        {
            booking_id: 1,
            user_id: 1,
            amount: 24000,
            payment_method: "Mpesa",
            payment_status: "completed",
            transaction_id: "TXN123456",
            payment_date: new Date(),
        },
        {
            booking_id: 2,
            user_id: 2,
            amount: 60000,
            payment_method: "Credit Card",
            payment_status: "pending",
            transaction_id: "TXN654321",
            payment_date: new Date(),
        },
        {
            booking_id: 3,
            user_id: 3,
            amount: 6000,
            payment_method: "Bank Transfer",
            payment_status: "completed",
            transaction_id: "TXN789123",
            payment_date: new Date(),
        },
        {
            booking_id: 4,
            user_id: 4,
            amount: 30000,
            payment_method: "Mpesa",
            payment_status: "completed",
            transaction_id: "TXN456789",
            payment_date: new Date(),
        },
        {
            booking_id: 5,
            user_id: 5,
            amount: 42000,
            payment_method: "Credit Card",
            payment_status: "pending",
            transaction_id: "TXN987123",
            payment_date: new Date(),
        },
        {
            booking_id: 6,
            user_id: 6,
            amount: 36000,
            payment_method: "Mpesa",
            payment_status: "completed",
            transaction_id: "TXN321654",
            payment_date: new Date(),
        },
        {
            booking_id: 7,
            user_id: 7,
            amount: 9000,
            payment_method: "Cash",
            payment_status: "pending",
            transaction_id: "TXN147258",
            payment_date: new Date(),
        },
        {
            booking_id: 8,
            user_id: 8,
            amount: 88000,
            payment_method: "Credit Card",
            payment_status: "completed",
            transaction_id: "TXN369852",
            payment_date: new Date(),
        },
        {
            booking_id: 9,
            user_id: 9,
            amount: 26000,
            payment_method: "Mpesa",
            payment_status: "completed",
            transaction_id: "TXN258147",
            payment_date: new Date(),
        },
        {
            booking_id: 10,
            user_id: 10,
            amount: 8000,
            payment_method: "Bank Transfer",
            payment_status: "pending",
            transaction_id: "TXN963741",
            payment_date: new Date(),
        }
    ]);

    // Seed Customer Support (10 records, linked to users)
    await db.insert(CustomerSupportTable).values([
        {
            user_id: 1,
            subject: "WiFi Issue",
            description: "WiFi not working in room 101.",
            status: "open",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 2,
            subject: "Late Check-in",
            description: "Requesting late check-in for booking.",
            status: "closed",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 3,
            subject: "Room Cleanliness",
            description: "Room was not properly cleaned.",
            status: "open",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 4,
            subject: "Booking Cancellation",
            description: "Need to cancel my booking due to change in plans.",
            status: "pending",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 5,
            subject: "Amenities Request",
            description: "Requesting extra towels for room 501.",
            status: "closed",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 6,
            subject: "Noise Complaint",
            description: "Loud noise from nearby room at night.",
            status: "open",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 7,
            subject: "Payment Issue",
            description: "Payment was charged twice.",
            status: "pending",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 8,
            subject: "Room Upgrade",
            description: "Requesting a room upgrade for my stay.",
            status: "closed",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 9,
            subject: "AC Malfunction",
            description: "Air conditioning not working in room 901.",
            status: "open",
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            user_id: 10,
            subject: "Early Check-in",
            description: "Requesting early check-in for my booking.",
            status:  "pending",
            created_at: new Date(),
            updated_at: new Date(),
        }
    ]);

    console.log('Database seeded successfully.');
}

seed()
    .then(() => {
        console.log('Seeding process completed.');
        process.exit(0);
    })
    .catch((error) => {
        console.error('Error seeding database:', error);
        process.exit(1);
    });